---
- name: Run show version on all devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands:
          - show version
      register: show_ver_output

    - name: Display output
      debug:
        msg: "{{ show_ver_output.stdout[0] }}"
